### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TheLimePixel** [talandar/ProgressiveDifficulty#2]
So I was just roaming around my world and I got this:
 https://pastebin.com/5qx813EZ

**Comment by talandar** [comment]
Thanks for the bug report.  I think I see the problem, and I should be able to get it fixed this afternoon.

If you keep running into crashes, or want to prevent them before I get the patch out, disable the AddDamageModifier (set `EnableAddDamageModifier=false` in the config) to prevent further crashes.

Is this a modpack on curse, or did you assemble this yourself?  I'd like to test my fix before declaring success.  It looks like one of the mods adds a mob without a "damage" attribute, which I didn't expect, so didn't protect against.  If you made it yourself, could you export your profile for me so that I can try it out?  I think you'll be able to upload the exported profile file to this bug ticket.

**Comment by talandar** [comment]
1.3.1 Fixes this issue, both in 1.11 and 1.12 versions.
