### ISSUE TITLE
[Suggestion] Add All Passive Creatures to Blacklist

### ISSUE THREAD

**Issue by ghost** [talandar/ProgressiveDifficulty#3]
It took me weeks of trying to figure out why passive creatures weren't spawning in my worlds, and which mod had caused it. Eventually, I figured out that by setting this mod's BaseDifficulty=-100, in combination with the default value of PreventLowDifficultySpawns=true, and a blacklist that only included bats and squids, I'd inadvertently caused all other passive mobs (excluding villagers, and a few creatures from other mods that don't register themselves properly) from spawning at all.

To avoid any similar confusion to other users, perhaps it would be a good idea to add all passive mobs (and mobs that can be mounts for hostile mobs, but become passive after the death of their riders) to the blacklist by default.

**Comment by talandar** [comment]
I had run into this problem in development, and have increased the default blacklist's size since the version you started with - but because you started out early, you got the smaller blacklist.  It's unfortunate that people using the mod longer will end up with a pretty bad blacklist...

I hadn't thought about generating a default blacklist from passive mobs and the like.  It's a good idea.  Not sure how I'd go about handling the mounted part, though...

If it helps, the default blacklist in the current version is 
Donkey
        Mule
        Bat
        Pig
        Sheep
        Cow
        Chicken
        Squid
        Wolf
        MushroomCow
        SnowMan
        Ozelot
        VillagerGolem
        Horse
        Rabbit
        Llama
        Parrot
        Villager

**Comment by ghost** [comment]
Ah okay, a legacy problem then, glad to see it's resolved in more recent versions, and thanks for the list!

**Comment by talandar** [comment]
So, good news bad news.
Good news, I found a way to fix your issue without forcing updates to the blacklist, and it should work much better in general.

Bad news, I have to open an entirely different bug that you probably won't like.  Check out bug #4 for details.
