### ISSUE TITLE
Skeletons Spawn when set to not spawn

### ISSUE THREAD

**Issue by talandar** [talandar/ProgressiveDifficulty#4]
Thanks to the minecraft bug [MC-103516](https://bugs.mojang.com/browse/MC-103516), spider riding skeletons spawn, but the spider does not.  The spawn of the skeleton doesn't throw all the events needed for standard spawning, so Progressive Difficulty doesn't catch it.

Maybe change progressive Difficulty to handle mobs spawned this way a little better.  This would also effect eggs and the like.

**Comment by ghost** [comment]
If 1% of skeletons and zombies (those that spawn as jockeys) are normal versus the 99% that are modified by Progressive Difficulty, I'd say it's not a huge disruption to play. Since it's an MC bug, I think it's on Mojang to fix, and not necessarily something you'd want to waste time creating a workaround for just to have to remove it later when the MC bug gets fixed. Since it's a bug that removes a tangible feature from Vanilla, I'd hope Mojang have an incentive to fix it.
